### ISSUE TITLE
希望支持markdown类型消息

### ISSUE THREAD

**Issue by WhiteYin** [lishewen/WeCom-ADOS-Extension#1]
[企业微信群机器人-markdown](https://work.weixin.qq.com/api/doc/90000/90136/91770#markdown%E7%B1%BB%E5%9E%8B)  
简单的普通文本不能满足多行信息通知的需要。

**Comment by lishewen** [comment]
收到，晚点弄下

**Comment by lishewen** [comment]
应该可以了，欢迎试下0.2.3版

**Comment by WhiteYin** [comment]
使用后，没有问题。
