### ISSUE TITLE
建议修改标题和描述以区分新旧两个插件

### ISSUE THREAD

**Issue by WhiteYin** [lishewen/WeCom-ADOS-Extension#2]
由于项目普遍使用了旧版的消息插件，无法完全弃用。  
所以在安装当前仓库对应的新版插件后会存在两个同名同描述的任务，如图：  
![image](https://user-images.githubusercontent.com/11420425/114646827-9764ca00-9d0e-11eb-8968-bcd3d0dd39bd.png)

如果误选了旧版，则需要重新操作一遍，不太方便。

**Comment by lishewen** [comment]
广西三月三放假旅游中，回来更新

**Comment by lishewen** [comment]
已更新
